/*
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends dk.itu.smdp.junit.asrt.AbstractMyDslRuntimeModule {

}
