/**
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.validation;

import dk.itu.smdp.junit.asrt.validation.AbstractMyDslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MyDslValidator extends AbstractMyDslValidator {
}
