/**
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.serializer;

import dk.itu.smdp.junit.asrt.serializer.AbstractMyDsl2SyntacticSequencer;

@SuppressWarnings("all")
public class MyDsl2SyntacticSequencer extends AbstractMyDsl2SyntacticSequencer {
}
