/**
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.serializer;

import dk.itu.smdp.junit.asrt.serializer.AbstractMyDsl2SemanticSequencer;

@SuppressWarnings("all")
public class MyDsl2SemanticSequencer extends AbstractMyDsl2SemanticSequencer {
}
