/**
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.validation;

import dk.itu.smdp.junit.asrt.validation.AbstractMyDsl2Validator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class MyDsl2Validator extends AbstractMyDsl2Validator {
}
