/**
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.ui.contentassist;

import dk.itu.smdp.junit.asrt.ui.contentassist.AbstractMyDslProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
