/**
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.serializer;

import dk.itu.smdp.junit.asrt.serializer.AbstractMyDslSemanticSequencer;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractMyDslSemanticSequencer {
}
