/**
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.serializer;

import dk.itu.smdp.junit.asrt.serializer.AbstractMyDslSyntacticSequencer;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractMyDslSyntacticSequencer {
}
