<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="junit" nsURI="http://junit/1.0" nsPrefix="junit">
  <eClassifiers xsi:type="ecore:EClass" name="root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//TestClass"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//Verifier"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JUnitCore">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Result"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Result">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Failure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Failure"/>
  <eClassifiers xsi:type="ecore:EClass" name="Suite" eSuperTypes="#//Class%20Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestClass">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//field"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//method"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//Class%20Annotation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//field"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Test" eSuperTypes="#//Method%20Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exception"/>
  <eClassifiers xsi:type="ecore:EClass" name="Before" eSuperTypes="#//Fixture%20Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="After" eSuperTypes="#//Fixture%20Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Before Class" eSuperTypes="#//Fixture%20Annotation">
    <eOperations name="EOperation0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="After Class" eSuperTypes="#//Fixture%20Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assertion"/>
  <eClassifiers xsi:type="ecore:EClass" name="field">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" lowerBound="1" eType="#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Field%20Annotation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//Field%20Annotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="method">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Method%20Annotation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//Assertion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//Assumption"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" upperBound="-1" eType="#//Method%20Annotation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Type" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuleType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="Method Rule" eSuperTypes="#//RuleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestRule" eSuperTypes="#//RuleType"/>
  <eClassifiers xsi:type="ecore:EClass" name="RuleAnnotation" eSuperTypes="#//Field%20Annotation #//Method%20Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fixture Annotation" eSuperTypes="#//Method%20Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rule" eSuperTypes="#//RuleAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassRule" eSuperTypes="#//RuleAnnotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expected" eSuperTypes="#//Method%20Annotation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="" eType="#//Exception"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" eType="#//Exception"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class Annotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Method Annotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Field Annotation" eSuperTypes="#//Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ignore" eSuperTypes="#//Method%20Annotation #//Class%20Annotation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Verifier" eSuperTypes="#//TestRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Timeout" eSuperTypes="#//TestRule"/>
  <eClassifiers xsi:type="ecore:EClass" name="Assumption"/>
  <eClassifiers xsi:type="ecore:EClass" name="Type"/>
</ecore:EPackage>
