/*
* generated by Xtext
*/
package dk.itu.smdp.junit.asrt;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyDsl2UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return dk.itu.smdp.junit.asrt.ui.internal.MyDsl2Activator.getInstance().getInjector("dk.itu.smdp.junit.asrt.MyDsl2");
	}
	
}
