/*
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.ui.contentassist

import dk.itu.smdp.junit.asrt.ui.contentassist.AbstractMyDsl2ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MyDsl2ProposalProvider extends AbstractMyDsl2ProposalProvider {
}
