/*
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.itu.smdp.junit.asrt.ui.internal.MyDsl2Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDsl2ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MyDsl2Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MyDsl2Activator.getInstance().getInjector(MyDsl2Activator.DK_ITU_SMDP_JUNIT_ASRT_MYDSL2);
	}
	
}
