/*
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslUiModule extends dk.itu.smdp.junit.asrt.ui.AbstractMyDslUiModule {
	public MyDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
