/*
* generated by Xtext
*/
package dk.itu.smdp.junit.asrt.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import dk.itu.smdp.junit.asrt.services.MyDsl2GrammarAccess;

public class MyDsl2Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MyDsl2GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected dk.itu.smdp.junit.asrt.parser.antlr.internal.InternalMyDsl2Parser createParser(XtextTokenStream stream) {
		return new dk.itu.smdp.junit.asrt.parser.antlr.internal.InternalMyDsl2Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public MyDsl2GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MyDsl2GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
