/*
* generated by Xtext
*/
package dk.itu.smdp.junit.asrt.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDsl2AntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("dk/itu/smdp/junit/asrt/parser/antlr/internal/InternalMyDsl2.tokens");
	}
}
