/*
 * generated by Xtext
 */
package dk.itu.smdp.junit.asrt.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDsl2UiModule extends dk.itu.smdp.junit.asrt.ui.AbstractMyDsl2UiModule {
	public MyDsl2UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
