<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="asrt" nsURI="http://www.itu.dk/people/wasowski/dk.itu.smdp.junit.asrt"
    nsPrefix="smdpjunitasrt">
  <eClassifiers xsi:type="ecore:EClass" name="AssertMethod" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" lowerBound="1"
        upperBound="-1" eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bodyExpr" lowerBound="1"
        eType="#//Exp" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//SimpleTypeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SimpleTypeEnum">
    <eLiterals name="BOOLEAN"/>
    <eLiterals name="OBJECT" value="1"/>
    <eLiterals name="DOUBLE" value="3" literal="DOUBLE"/>
    <eLiterals name="LONG" value="4"/>
    <eLiterals name="SHORT" value="6"/>
    <eLiterals name="INT" value="7"/>
    <eLiterals name="FLOAT" value="8"/>
    <eLiterals name="CHAR" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exp" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UOp" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Const" abstract="true" eSuperTypes="#//Exp"/>
  <eClassifiers xsi:type="ecore:EClass" name="NULL" eSuperTypes="#//Const"/>
  <eClassifiers xsi:type="ecore:EClass" name="Id" eSuperTypes="#//NamedElement #//Exp"/>
  <eClassifiers xsi:type="ecore:EClass" name="BOp" eSuperTypes="#//Exp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lexpr" lowerBound="1" eType="#//Exp"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rexpr" lowerBound="1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BOpMethod" eSuperTypes="#//BOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunCall" eSuperTypes="#//NamedElement #//Exp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="arg" upperBound="-1" eType="#//Exp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assertMethods" upperBound="-1"
        eType="#//AssertMethod" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
